### ISSUE TITLE
Behavior improvement for dev-server on fresh install

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#144]
I recently upgraded to f32. I wanted to build the flash code here is what I did:

- bash dev-server.sh
-  error: docker not found
- radia_run redhat-docker
- log out/in
- bash dev-server.sh
- bash dev-build.sh common
- error: `docker: Error response from daemon: pull access denied for radiasoft/fedora, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

Couple things:
1. It doesn't make sense that I had to install docker. dev-setup.sh should do that for me. Not sure what's going on.
2. $radiasoft_repo_file needs to be removed if the dev-setup.sh fails because docker not found or we need a better sentinel for when to run dev-setup.sh. Otherwise next time the dev-server is started the file is found and the image won't be created.

**Comment by robnagler** [comment]
Thanks. I think it should fail at not finding docker (first check) and have it output the redhat-docker message, because you actually have to logout and login. Possibly could do a exec sudo su - vagrant, but that would be tricky to continue at the script...

We could add a flag to sirepo-dev to run this, or just have it install docker, which would obviate the logout/login above. It makes sirepo-dev a bit long to run, but maybe that makes the most sense, since technically it's needed for supervisor development. 

Thoughts?
