### ISSUE TITLE
standardize patch style?

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#195]
We have at least two different styles of patches ([here](https://github.com/radiasoft/download/blob/f4fe1c61b8200a25d5f338e9a5fbcfe7e1534343/installers/rpm-code/codes/opal.sh#L52) and [here](https://github.com/radiasoft/download/blob/f4fe1c61b8200a25d5f338e9a5fbcfe7e1534343/installers/rpm-code/codes/raydata.sh#L29)). 

I think it makes sense to settle on one style for the usual reasons (reducing cognitive overload, standard style, etc).

What style do people prefer? 

I have a slight preference for unified and no context (`diff --unified=0`) . Unified is similar to git so I think more people will be familiar with it (I can read it better). No context to reduce lines of code and I don't think context provides much value here.

**Comment by robnagler** [comment]
I'm so used to context patches that I struggle with the idea that line numbers are enough. Context provides backwards compatibility checking. If any of the context changes, the patch fails. We don't control the source we are patching (or we wouldn't be patching) so I think that's why I'm concerned. 

With fixed versions, perhaps that's different. However, I don't always trust binary downloads to be unmodified even though the file name doesn't change.

Not strong preferences, just my sense of things.

**Comment by e-carlin** [comment]
Ok, adding context makes sense. How about unified with context? The default lines of context for both `--context` and `--unified` is 3 lines. So we could do `diff --unified`.

**Comment by robnagler** [comment]
That's fine. How do we document this? We don't exactly have documentation on downloaders or codes.

**Comment by e-carlin** [comment]
Great. I added a [style guide wiki](https://github.com/radiasoft/download/wiki/Style-guide). Good?

**Comment by robnagler** [comment]
Thanks for doing that. I now need to remember. :)
