### ISSUE TITLE
Compiling on host issue

### ISSUE THREAD

**Issue by abdoudiaw** [radiasoft/download#199]
I am trying to compile Smilei, but since the python library is not in the default path, it can't figure out where it is located.  Here is the error message I am getting:

```
/usr/bin/ld: cannot find -lpython3.7m
collect2: error: ld returned 1 exit status
```
Setting the python path to:
```
LDFLAGS="-L/home/vagrant/.pyenv/versions/3.7.2/lib/"
```
does not fix the issue

Assignee: @e-carlin

**Comment by robnagler** [comment]
The value of `$(pyenv prefix)` may be helpful if you know here to supply it.

**Comment by abdoudiaw** [comment]
This issue was fixed by setting the path path and environment variable to
`export PYTHONHOME=/home/vagrant/.pyenv/versions/3.7.2/`
`export LD_LIBRARY_PATH=/lib:/usr/lib:/home/vagrant/.pyenv/versions/3.7.2/lib`

**Comment by robnagler** [comment]
I suspect there's more going on here, but your solution obviously works.

However, you should not refer to 3.7.2 directly (since it is the `py3` virtualenv that we use). The better values would be:

```sh
export PYTHONHOME="$(pyenv prefix)"
bivio_ld_library_path_insert "$PYTHONHOME/lib"
```

Just FYI, /lib and /usr/lib are identical:

```py
$ ls -al /lib
lrwxrwxrwx. 1 root root 7 Jan 28  2020 /lib -> usr/lib
```

/usr/lib and /usr/lib64 are always searched so you never need to add them.

There may be other values in LD_LIBRARY_PATH (such as /usr/lib64/mpich/lib) which you would want to leave unmodified, that's what bivio_ld_library_path_insert does. If you are running in a shell script, this would work:

```sh
export LD_LIBRARY_PATH="$(pyenv prefix)/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
```
