### ISSUE TITLE
nersc-sirepo-update should check python version == $install_version_python

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#454]
If they aren't equal it should update the python version. This will allow us to release f36 with py3.9.

Our script for running releases should be adapted to set install_version_python in the nersc-sirepo-update command printed out. This will allow us to cascade the python version from the build server to NERSC.

**Comment by e-carlin** [comment]
@robnagler please confirm this approach sounds ok

**Comment by e-carlin** [comment]
I don't understand your comment. Can you elaborate?

**Comment by robnagler** [comment]
The venvs look like this:

```sh
(py3) nagler@cori05:~/.pyenv/versions> ls -altr
total 14
drwxr-xr-x  7 nagler nagler  512 Nov 30  2019 3.7.2
lrwxrwxrwx  1 nagler nagler   53 Nov 30  2019 py3 -> /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/py3
lrwxrwxrwx  1 nagler nagler   62 Jan  8  2020 sirepo-alpha -> /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha
lrwxrwxrwx  1 nagler nagler   61 Feb 11  2020 sirepo-beta -> /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-beta
lrwxrwxrwx  1 nagler nagler   61 Feb 18  2020 sirepo-prod -> /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-prod
```

You need to `pyenv install 3.9.x` before deleting `sirepo-alpha` and recreating it. However, you don't need to do that when updating `sirepo-beta`, because 3.9.x will already exist. 

As to the pyenv itself, you "could" dynamically set `$PYENV_ROOT` for alpha, beta, etc. so that you could test the version of pyenv in alpha before updating beta. I think that's overboard, but that's what I meant by that.

**Comment by e-carlin** [comment]
Ah ok
